### ISSUE TITLE
Implement automatic task lists

### ISSUE THREAD

**Issue by kzu** [kzu/sandbox#495]
Create and maintain task lists on referenced issues.

> This task list is updated automatically when the referenced issues are closed or reopened, via <a href="http://goo.gl/iB4ZFR" title="Learn more about OctoHook's AutoTask"><img src="http://goo.gl/8P3okW" /></a>
- [x] #496 Find linked issues in a story body
- [x] #497 Create task list on referenced issue
- [x] #498 Skip task list links
- [ ] #499 Support cross-repository links
